server:
  port: 7777
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sg_blog?useUnicode=true&characterEncoding=utf-8
    username: root
    password: FTNATSULOL1

  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 5MB
  redis:
    host: 192.168.206.128
mybatis-plus:
  configuration:
    # 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto
oss:
  accessKey: hxkVSa5YEsIWO2ktUlhnv9fvpmA6XNAGCje9T-Wq
  secretKey: YOJDgk1sx8Z_790ixxT_jMW0euYh2Xm1XeXQg9cu
  bucket: sgblog30